AddContentTemplateMigrationResilency-GP
Ortus-Solutions/ContentBox pull request #580
Opened 2023-09-25 19:00 UTC by gpickin

Make the ContentTemplate migration more resilient.

Check for the table
Then check for the columns and only add the column and indexes if they don't exist.

2023-09-25 19:49 UTC, jclausen requested changes
A couple of tweaks and then this is good to merge.

2023-09-25 19:49 UTC, jclausen commented on modules/contentbox/migrations/_MigrationUtils.cfm
There's no need for this method or compoinent. You can just use the `.hasTable` method on the schema.

```
if ( !schema.hasTable( "cb_contentTemplate" ) )
```

2023-09-25 19:49 UTC, jclausen commented on modules/contentbox/migrations/2023_07_13_092814_v_6_0_0_ContentTemplates.cfc
> +		if ( !hasTable( "cb_contentTemplate" ) ) {
Let's make this conditional an if/else. If the table exists, let's make sure the column typing and lengths ( for the non-key columns ) are correct.  Let's also make sure the `idx_contentType` index gets created.

2023-09-26 11:29 UTC, lmajano commented on modules/contentbox/migrations/_MigrationUtils.cfm
There's a reason it's there.

2023-09-26 13:51 UTC, jclausen commented on modules/contentbox/migrations/_MigrationUtils.cfm
@elpete [Fixed that 5  years ago](https://github.com/coldbox-modules/qb/blame/main/models/Grammars/BaseGrammar.cfc#L1719), I believe.  You wouldn't be able to get in to this or any migration if `hasTable` wasn't working because `cfmigrations` runs that method to determine if it's own table exists.  I didn't noticed that there were other UDFs in this component, though.  I thought this mixin was added. My bad. I would still stand challenging the need for the separate method, though.

2023-09-26 18:26 UTC, lmajano commented on modules/contentbox/migrations/_MigrationUtils.cfm
Not as of a few weeks unless he fixed
It recently. It was the same issue on columns. 

The problem was that if you have a database with multiple schemas with ContentBox it would
Use any schema. It was not using the appropriate schema constraints. Maybe @elpete van corroborate.

2023-10-18 11:01 UTC, lmajano commented
I merged manually

2023-10-18 11:01 UTC, closed without merging